version: "3.9"

networks:
  nktc_stu:
    external: true

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#       - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
#     command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      nktc_stu:
        ipv4_address: 172.20.0.50
        
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nktc_stu

  portainer:
    image: portainer/portainer-ce
    container_name: potainer
    privileged: true
    ports:
      - "9100:9000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - TZ=Asia/Bangkok
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9100 || exit 1"
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - nktc_stu

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      nktc_stu:
        ipv4_address: 172.20.0.100

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    user: root
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
    environment:
      TZ: "Asia/Bangkok"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/login" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    networks:
      - nktc_stu
volumes:
  postgres_data:
  pgadmin_data:
  minio_storage:
  jenkins_home:
