version: "3.9"

networks:
  nktc_stu:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres-data:
  pgadmin-data:
  minio_storage:

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    env_file:
      - .env
    ports:
      - "172.20.0.50:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      nktc_stu:
        ipv4_address: 172.20.0.50

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - nktc_stu

  portainer:
    image: portainer/portainer-ce
    container_name: potainer
    privileged: true
    ports:
      - "9100:9000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - nktc_stu

  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" /data
    ports:
      - "172.20.0.100:9000:9000"
      - "172.20.0.100:9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      nktc_stu:
        ipv4_address: 172.20.0.100
